# Generated by Django 3.2.25 on 2024-03-21 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('age', models.CharField(max_length=10)),
                ('gender', models.CharField(max_length=70)),
                ('locality', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=50)),
                ('number', models.CharField(max_length=20)),
            ],
        ),
    ]
